enabled: true
logo: logo.png
footer_icons:
  -
    icon: 'fa fa-twitter'
    url: 'https://www.twitter.com/drchuck'
footer_blocks:
  -
    title: 'Open Hosting / Open Source'
    content: 'This server provides community-supported hosting of open source <a href="https://www.tsugi.org" target="_blank">Tsugi</a> educational tools available in the <a href="https://github.com/tsugitools" target="_blank">Tsugi Tools Project</a>.'
    logo: false
    icons: false
  -
    title: 'Support Open Source'
    content: 'This service is provided to help support and grow the Tsugi community.  You can help support this effort by becoming involved in the <a href="https://www.apereo.org" target="_blank">Apereo</a> community.'
    logo: false
    icons: false
google_maps_api_key: AIzaSyDbmnZP5BTkpv5blTprRtUvS99zbvyoSAQ
